# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for Maya MCP server
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and source
COPY requirements.txt ./
COPY src ./src

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Create log directory
RUN mkdir -p /app/src

# Default command
ENTRYPOINT ["python", "src/maya_mcp_server.py"]
